### ISSUE TITLE
Get dhall-nix on stackage

### ISSUE THREAD

**Issue by domenkozar** [dhall-lang/dhall-nix#10]
To avoid https://github.com/dhall-lang/dhall-nix/issues/9 in the future, we should get dhall-nix to LTS-12.X and nightly again. I'm willing to help on this front and be stackage co-maintainer. 

cc @Gabriel439

**Comment by Gabriella439** [comment]
Yeah, feel free register as a co-maintainer of `dhall-nix` on Stackage

My understanding is that the main blocker here is getting `hnix` on Stackage.  It used to be there but eventually got removed

**Comment by domenkozar** [comment]
https://github.com/commercialhaskell/lts-haskell/issues/146

**Comment by Gabriella439** [comment]
I'm closing out issues before archiving this repository since `dhall-nix` is moving into the `dhall-haskell` project.

We're a step closer to getting this on Stackage now that `hnix` supports the latest `megaparsec`.  There are still some issues with `hnix` that require building against the GitHub version instead of Stackage, but once it's Stackage-ready I'll add it
