### ISSUE TITLE
Types transform to {}

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-nix#20]
```
$ dhall-to-nix <<< '+4 : Integer'
4

$ dhall-to-nix <<< 'Integer'
{}
```

This is a bit strange, we might want to abort in that case.

**Comment by Gabriella439** [comment]
@Profpatsch: This is intentional, although there is room for improvement

The rationale is that `dhallToNix "f a"` should always produce the same result as `dhallToNix "f" (dhallToNix "a")`

For example:

```haskell
dhallToNix "List/head" (dhallToNix "Natural") (dhallToNix "[ 1 ]")

= (_: xs: if xs == [] then null else builtins.head xs) {} [ 1 ]

= (xs: if xs == [] then null else builtins.head xs) [ 1 ]

= 1

= dhallToNix "List/head Natural [ 1 ]"
```

The reason that I say that there is more room for improvement is that we could actually use a more sophisticated representation for types (i.e. anything other than `{}`).  For example, a type like `{ foo : Natural, bar : Bool }` could be translated to Nix as something like `{ foo = "Natural"; bar = "Bool"; }` (or something similar).  The only reason I didn't do that is that I couldn't find a use for it in the translation to Nix and I was lazy.

**Comment by Gabriella439** [comment]
I'm closing this out since I'm archiving the repository and I believe this was answered.  For any additional questions, open up an issue against the repository's new home here: https://github.com/dhall-lang/dhall-haskell/issues
